### ISSUE TITLE
Error in RandomBaseDataModel.angular.extend.init

### ISSUE THREAD

**Issue by gabrielacosta** [dtpublic/malhar-dashboard-webapp#2]
Good Afternoon, 

I just download and setup the dashboard. I run it and generally speaking it works fine. 

However, the wt-line-chart is giving me problems. It does not render and it throws a javascript error.

TypeError: Cannot read property 'change' of undefined
    at RandomBaseDataModel.angular.extend.init (http://127.0.0.1:9000/bower_components/malhar-angular-widgets/dist/malhar-angular-widgets.js:50:45)
    at RandomBaseDataModel.RandomTimeSeriesDataModel.init (http://127.0.0.1:9000/bower_components/malhar-angular-widgets/dist/malhar-angular-widgets.js:132:42)
    at link (http://127.0.0.1:9000/bower_components/malhar-angular-dashboard/dist/angular-ui-dashboard.js:483:14)
    at nodeLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:6676:13)
    at compositeLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:6070:13)
    at publicLinkFn (http://127.0.0.1:9000/bower_components/angular/angular.js:5966:30)
    at boundTranscludeFn (http://127.0.0.1:9000/bower_components/angular/angular.js:6090:21)
    at controllersBoundTransclude (http://127.0.0.1:9000/bower_components/angular/angular.js:6697:18)
    at ngRepeatAction (http://127.0.0.1:9000/bower_components/angular/angular.js:20502:15)
    at Object.$watchCollectionAction [as fn](http://127.0.0.1:9000/bower_components/angular/angular.js:12342:13) <div ng-repeat="widget in widgets" ng-style="widget.style" class="widget-container ng-scope" widget="">

I track the issue to the bower_components/malhar-angular-widgets.  I check the version version of angular.js in bower_components/angular and compare with the last version in git and everything is correct.

Could you please take a look and guide how to solve this issue.

I really like the dashboard that you create. Very clean and nice job.

**Comment by nickholub** [comment]
Yes, there were a lot of changes in dashboard component and the widgets recently.
Going to fix this. wt-line-chart line chart demo in malhar-angular-widgets should work.

**Comment by gabrielacosta** [comment]
I just download the code from the master source and unfortunately it gives my that error.
Really it gives me two  one with utf in the d3.js, easy to solve.
However, the other one I don't know how to fixed it. Could you give a hint, how to solve it? If I fixed I will fork the project and upload it back.

**Comment by nickholub** [comment]
I have updated the project. Please refetch bower dependencies. It should work now.
You can also check https://github.com/DataTorrent/malhar-angular-widgets
It has original charts and demo as well.

**Comment by gabrielacosta** [comment]
Thanks Nick, I just download it and it works perfect. 
Nick may I ask you something about the use of the controls.
I check the code inside demo and the controls works perfect. I have a doubt about how to manage different data for the same controls. For example, If I clean the dashboard and create several wt-gauge controls all will show the same information. 

The function that manage that value will put the same value for any instance. 

 $scope.percentage = 5;
    $interval(function () {
      $scope.percentage = ($scope.percentage + 10) % 100;
    }, 1000);

How can I manage different values for each new control? How can I differentiate them inside the js for modify their properties. There is any way to link the Widgetdefinitions with some specific identifier?

**Comment by gabrielacosta** [comment]
Nevermind Nick, I just figured it out. The problem was I'm begginer in angular and it was give me some problems. Thanks for your help.
