### ISSUE TITLE
TypeError: _.merge is not a function

### ISSUE THREAD

**Issue by ticlaudeberube** [dtpublic/malhar-dashboard-webapp#6]
There is an issue with underscore and lodash.  _.merge is undefined.

 at Object.WidgetModel (http://localhost:9000/bower_components/malhar-angular-dashboard/dist/malhar-angular-dashboard.js:848:42)

// Extend this with the widget definition object with overrides merged in (deep extended).
      angular.extend(this, defaults(), _.merge(angular.copy(widgetDefinition), overrides));

**Comment by ticlaudeberube** [comment]
Replaced _underscore with lodash in /app/index.html.  Wondering what is _underscore dependency for?

**Comment by deepthiravadi** [comment]
HI, I am trying to resolve this bug, I included underscore.js and loadash.js files, but it still throws me the below error

 _.merge is not a function
    at Object.WidgetModel (/js/angular/angular-ui-dashboard.js:848:56)

can you please help..

**Comment by shadeeka** [comment]
Is anybody able to resolve this.. I am also getting the same error.
can anyone help ... thank you

**Comment by ticlaudeberube** [comment]
Yes,  I got it working I believe by using loadash instead of underscore.

Claude

Claude Bérubé, PMP, PSM
claude.berube@gmail.com
514-529-0338

_http://cberube.azurewebsites.net/ http://cberube.azurewebsites.net/_

2015-10-15 21:24 GMT-04:00 shadeeka notifications@github.com:

**Comment by vladradulescu1** [comment]
thanks man, I removed underscore.js also and it works just fine !!

**Comment by lazyTai** [comment]
![image](https://user-images.githubusercontent.com/16125707/39428027-8962525a-4cb8-11e8-9669-69b3a72d2387.png)

**Comment by praveesh91** [comment]
fixed???

**Comment by biomagic** [comment]
I have the same error when include lodash to require.js. 
![2020-10-08_110455](https://user-images.githubusercontent.com/17408368/95431686-425a8c80-0956-11eb-8c32-e5e8ec1bd875.jpg)

My **config.js** file:

```
requirejs.config({
  baseUrl: myAppUri,
  paths: {
    jquery: 'lib/jquery.min',
    lodash: 'lib/lodash.min',
    emitter: 'app/emitter',
    base: 'app/base',
  },
  config: {
    '_@r6': {
      base: {

      },
    }
  }
});

require(['module', 'emitter', 'jquery', 'lodash', 'base'],
function(module, emitter, $, _, Base) {
  _.merge({}, {});
});
```

When it will be fixed? 5 years have passed since the theme was created.
